//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class factors_old
    {
        public int id { get; set; }
        public string site { get; set; }
        public string names { get; set; }
        public string category { get; set; }
        public string global_category { get; set; }
        public int game_id { get; set; }
        public string link { get; set; }
        public string time { get; set; }
        public int type { get; set; }
        public Nullable<float> p1 { get; set; }
        public Nullable<float> p2 { get; set; }
        public Nullable<float> x { get; set; }
        public Nullable<float> x1 { get; set; }
        public Nullable<float> x12 { get; set; }
        public Nullable<float> x2 { get; set; }
        public Nullable<float> m { get; set; }
        public Nullable<float> t { get; set; }
        public Nullable<float> b { get; set; }
        public Nullable<float> f1 { get; set; }
        public Nullable<float> f2 { get; set; }
        public Nullable<float> k1 { get; set; }
        public Nullable<float> k2 { get; set; }
        public Nullable<float> kf1 { get; set; }
        public Nullable<float> kf2 { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
