//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForksEntities : DbContext
    {
        public ForksEntities()
            : base("name=ForksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<factors> factors { get; set; }
        public virtual DbSet<forks> forks { get; set; }
        public virtual DbSet<game_names> game_names { get; set; }
        public virtual DbSet<matches> matches { get; set; }
        public virtual DbSet<pages> pages { get; set; }
        public virtual DbSet<temp> temp { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
