//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class forks
    {
        public long id { get; set; }
        public string key { get; set; }
        public int category_id { get; set; }
        public string champ { get; set; }
        public int game_id_1 { get; set; }
        public int game_id_2 { get; set; }
        public string name_1 { get; set; }
        public string name_2 { get; set; }
        public string site_1 { get; set; }
        public string site_2 { get; set; }
        public string type_1 { get; set; }
        public string type_2 { get; set; }
        public float k_1 { get; set; }
        public float k_2 { get; set; }
        public float plus { get; set; }
        public string type_g { get; set; }
        public string type_ru { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public string time_1 { get; set; }
        public string time_2 { get; set; }
    }
}
