//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class matches
    {
        public decimal id { get; set; }
        public int category_id { get; set; }
        public string site1 { get; set; }
        public string game1 { get; set; }
        public string site2 { get; set; }
        public string game2 { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
