//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string fun_class { get; set; }
        public string fun_name { get; set; }
        public string server { get; set; }
        public int port { get; set; }
        public int queue { get; set; }
        public bool status { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
